import { z } from 'zod';


export const SaveProjectSchema = z
   .object({
      // account_id: z.z.string()().uuid(),
      // project_name: z.z.string()().min(1),
      // title: z.z.string()().min(1),
      // platform: z.z.string()(),
      // topic: z.z.string()(),
      // subtopic: z.z.string()().nullable(),
      // state: z.boolean(),
      // mode: z.z.string()(),
      // start_date: z.z.string()(),
      // end_date: z.z.string()(),
      // created_by: z.z.string()().uuid(),
      // updated_by: z.z.string()().uuid().nullable(),
      pUserId: z.string().uuid(),
      pName: z.string(),
      pMainTopic: z.string(),
      pSubTopic: z.string(),
      pMode: z.string(),
      pState: z.boolean(),
      pStartDate: z.string(),
      pEndDate: z.string(),
      pPlatform: z.string(),
      pPlatformurl: z.string(),
      pCnt: z.number(),
      pAtmosphere: z.string(),
      pPostMode: z.string(),
      pTitle: z.string(),
      pTextContent: z.string(),
      pGeneratedTitles: z.string(),
      pImages: z.string(),
      pImageBrand: z.string(),
      pImageFormat: z.string(),
      pImageCnt: z.number(),
      pImageRatio: z.string(),
      pUseText: z.boolean(),
      pUseImage: z.boolean(),
      pUseVideo: z.boolean(),
   })